name: base-build
on:
  workflow_call:
    inputs:
      path:
        description: 'build dirs'
        type: string
        required: true
      file:
        description: 'build output file'
        type: string
        required: true
      CI_GOOS:
        type: string
        required: true
      CI_GOARCH:
        type: string
        required: true
      TAGS:
        type: string
        default: ""

jobs:
  base-build:
    runs-on: ubuntu-20.04
    container:
      image: veinmind/go1.18:1.3.1-stretch
    env:
      CI_GOOS: ${{inputs.CI_GOOS}}
      CI_GOARCH: ${{inputs.CI_GOARCH}}
      TAGS: ${{inputs.TAGS}}
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{inputs.path}} && /bin/bash -x script/build_${{inputs.CI_GOARCH}}.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.file}}-${{inputs.CI_GOARCH}}
          path: ${{inputs.path}}/artifacts/${{inputs.CI_GOOS}}-${{inputs.CI_GOARCH}}/${{inputs.file}}_${{inputs.CI_GOOS}}_${{inputs.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{inputs.path}}/artifacts/${{inputs.CI_GOOS}}-${{inputs.CI_GOARCH}}/${{inputs.file}}_${{inputs.CI_GOOS}}_${{inputs.CI_GOARCH}}