# because of arm build not support yet, so go plugin just only has amd64
name: push plugins amd64
on:
  workflow_call:
    inputs:
      path:
        description: 'package dirs'
        type: string
        required: true
      file:
        description: 'package output file'
        type: string
        required: true
      CI_GOOS:
        type: string
      CI_GOARCH:
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  base-push:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/${{ inputs.file }}:latest
            veinmind/${{ inputs.file }}:${{github.ref_name}}
          context: ${{ inputs.path }}
          build-args: |
            CI_GOOS=${{inputs.CI_GOOS}}
            CI_GOARCH=${{inputs.CI_GOARCH}}