name: veinmind-tools-push
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  # push python plugins
  push-python-plugins:
    strategy:
      matrix:
        plugin: [
          veinmind-backdoor,
          veinmind-history
        ]
        path: [ ./plugins/python/ ]
    name: ${{ matrix.plugin }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            dvkunion/${{ matrix.plugin }}:latest
            dvkunion/${{ matrix.plugin }}:${{github.ref_name}}
          context: ${{ matrix.path }}/${{ matrix.plugin }}
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}
  # push go plugins
  push-go-plugins:
    strategy:
      matrix:
        plugin: [
          veinmind-basic,
          veinmind-escalate,
          veinmind-iac,
          veinmind-log4j2,
          veinmind-malicious,
          veinmind-sensitive,
          veinmind-unsafe-mount,
          veinmind-vuln,
          veinmind-weakpass,
          veinmind-webshell,
        ]
        path: [ ./plugins/go/ ]
    name: ${{ matrix.plugin }}
    runs-on: ubuntu-20.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
#            linux/arm64
          tags: |
            dvkunion/${{ matrix.plugin }}:latest
            dvkunion/${{ matrix.plugin }}:${{github.ref_name}}
          context: ${{ matrix.path }}/${{ matrix.plugin }}
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}

  push-veinmind-runner:
    needs: [ push-python-plugins, push-go-plugins ]
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
#            linux/arm64
          tags: |
            dvkunion/veinmind-runner:latest
            dvkunion/veinmind-runner:${{github.ref_name}}
          context: veinmind-runner
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}