name: veinmind-tools
on: [push, pull_request]
jobs:
  package-veinmind-backdoor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd ./plugins/python/veinmind-backdoor
          tar -cvzf veinmind-backdoor.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-backdoor.tar.gz
          path: ./plugins/python/veinmind-backdoor/veinmind-backdoor.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/python/veinmind-backdoor/veinmind-backdoor.tar.gz
  package-veinmind-sensitive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd ./plugins/python/veinmind-sensitive
          tar -cvzf veinmind-sensitive.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-sensitive.tar.gz
          path: ./plugins/python/veinmind-sensitive/veinmind-sensitive.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/python/veinmind-sensitive/veinmind-sensitive.tar.gz
  package-veinmind-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd ./plugins/python/veinmind-history
          tar -cvzf veinmind-history.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-history.tar.gz
          path: ./plugins/python/veinmind-history/veinmind-history.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/python/veinmind-history/veinmind-history.tar.gz
  build-amd64-veinmind-malicious:
    runs-on: ubuntu-18.04
    container:
      image: veinmind/go1.18:1.3.1-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: cd ./plugins/go/veinmind-malicious && /bin/bash -x scripts/build_veinmind_malicious_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-malicious-amd64
          path: ./plugins/go/veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/go/veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  test-veinmind-weakpass:
    runs-on: ubuntu-20.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: |
          cd ./plugins/go/veinmind-weakpass && go mod tidy 
          cd hash && go test -tags static  && go test -tags dynamic
          cd ../service && go test -tags static  && go test -tags dynamic 
    
  build-amd64-static-veinmind-weakpass:
    runs-on: ubuntu-20.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "static"
    needs:  test-veinmind-weakpass
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd ./plugins/go/veinmind-weakpass && /bin/bash -x script/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64
          path: ./plugins/go/veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/go/veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-dynamic-veinmind-weakpass:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    container:
      image: veinmind/go1.18:1.3.1-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "dynamic"
    needs: test-veinmind-weakpass
    steps:
      - uses: actions/checkout@v2
      - run: cd ./plugins/go/veinmind-weakpass && /bin/bash -x script/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
          path: ./plugins/go/veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-veinmind-asset:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd ./plugins/go/veinmind-asset && /bin/bash -x script/build_veinmind_asset_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-asset-amd64
          path: ./plugins/go/veinmind-asset/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-asset_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-veinmind-runner:
    runs-on: ubuntu-latest
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    needs: build-amd64-static-veinmind-weakpass
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd veinmind-runner && /bin/bash -x script/build_veinmind_runner_amd64.sh
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-weakpass-amd64
      - run: |
          mv veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}} veinmind-weakpass
          mv ./veinmind-runner/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-runner_${{env.CI_GOOS}}_${{env.CI_GOARCH}} veinmind-runner-entrypoint
          rm -rf ./veinmind-runner && mv veinmind-runner-entrypoint veinmind-runner
          tar cvzf veinmind-runner.tar.gz veinmind-runner veinmind-weakpass ./plugins/python/veinmind-sensitive ./plugins/python/veinmind-history ./plugins/python/veinmind-backdoor
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-runner.tar.gz
          path: veinmind-runner.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: veinmind-runner.tar.gz
  build-amd64-veinmind-webshell:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd ./plugins/go/veinmind-webshell && /bin/bash -x script/build_veinmind_webshell_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-webshell-amd64
          path: ./plugins/go/veinmind-webshell/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-webshell_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/go/veinmind-webshell/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-webshell_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-veinmind-log4j2:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd ./plugins/go/veinmind-log4j2 && /bin/bash -x script/build_veinmind_log4j2_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-log4j2-amd64
          path: ./plugins/go/veinmind-log4j2/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-log4j2_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./plugins/go/veinmind-log4j2/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-log4j2_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  push-veinmind-backdoor:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-backdoor:latest
            veinmind/veinmind-backdoor:${{github.ref_name}}
          context: ./plugins/python/veinmind-backdoor
  push-veinmind-sensitive:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-sensitive:latest
            veinmind/veinmind-sensitive:${{github.ref_name}}
          context: ./plugins/python/veinmind-sensitive
  push-veinmind-history:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-history:latest
            veinmind/veinmind-history:${{github.ref_name}}
          context: ./plugins/python/veinmind-history
  push-veinmind-malicious:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64-veinmind-malicious
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-malicious-amd64
      - run: mv veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./plugins/go/veinmind-malicious
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-malicious:latest
            veinmind/veinmind-malicious:${{github.ref_name}}
          context: ./plugins/go/veinmind-malicious
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}
  push-veinmind-weakpass:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64-dynamic-veinmind-weakpass
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
      - run: mv veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-weakpass
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-weakpass:latest
            veinmind/veinmind-weakpass:${{github.ref_name}}
          context: ./plugins/go/veinmind-weakpass
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}
  push-veinmind-asset: 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-asset:latest
            veinmind/veinmind-asset:${{github.ref_name}}
          context: ./plugins/go/veinmind-asset
  push-veinmind-webshell:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-webshell:latest
            veinmind/veinmind-webshell:${{github.ref_name}}
          context: ./plugins/go/veinmind-webshell
  push-veinmind-log4j2:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-log4j2:latest
            veinmind/veinmind-log4j2:${{github.ref_name}}
          context: ./plugins/go/veinmind-log4j2
  push-veinmind-runner:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    needs: [push-veinmind-backdoor, push-veinmind-sensitive, push-veinmind-history, push-veinmind-malicious, push-veinmind-weakpass, push-veinmind-asset, push-veinmind-log4j2]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-runner:latest
            veinmind/veinmind-runner:${{github.ref_name}}
          context: ./veinmind-runner
