name: veinmind-malicious
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-18.04
    container:
      image: veinmind/go1.16:1.0.4-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: cd veinmind-malicious && /bin/bash -x ../scripts/build/build_veinmind_malicious_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-malicious-amd64
          path: ./veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  push-amd64-image:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-malicious-amd64
      - run: mv veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-malicious
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-malicious:latest
            veinmind/veinmind-malicious:${{github.ref_name}}
          context: ./veinmind-malicious
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}